on: {push, pull_request}

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make build
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip3 install ansible molecule[docker] docker molecule[lint]
      
      - run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip3 install ansible molecule[docker] docker molecule[lint]

      - run: make test